# k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app
  labels:
    app: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-app
  template:
    metadata:
      labels:
        app: chat-app
    spec:
      containers:
        - name: chat-app
          image: bleron2024/m324:latest    # oder dein Repo/Image
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: chat-app
spec:
  type: ClusterIP
  selector:
    app: chat-app
  ports:
    - port: 80
      targetPort: 3000
