# .github/workflows/cd.yml
name: CD Pipeline

on:
  push:
    branches: [master, development]
  workflow_dispatch:

jobs:
  deploy:
    # <-- Hier beginnt dein neuer Job
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install k3d
        run: |
          curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash

      - name: Create k3d cluster
        run: |
          k3d cluster create ci-test --wait

      - name: Build Docker image
        run: |
          docker build -t chat-app:ci .

      - name: Load image into k3d
        run: |
          k3d image import chat-app:ci -c ci-test

      - name: Deploy to k3d
        run: |
          kubectl apply -f k8s/deployment.yaml --context k3d-ci-test
          kubectl rollout status deployment/chat-app --context k3d-ci-test

      - name: Delete k3d cluster
        if: always()
        run: |
          k3d cluster delete ci-test
  
