# .github/workflows/cd.yml
name: CD Pipeline

on:
  push:
    branches: [master, development]
  workflow_dispatch:

jobs:
  deploy:
    name: Build, Push & Deploy to Kubernetes
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USER }}/m324:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USER }}/m324:latest

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure kubeconfig
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path "$HOME\.kube" -Force | Out-Null
          [System.IO.File]::WriteAllBytes(
            "$HOME\.kube\config",
            [System.Convert]::FromBase64String("${{ secrets.KUBE_CONFIG_DATA }}")
          )

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl rollout status deployment/chat-app
