name: CI Pipeline

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  ci:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Build app
        run: npm run build

      - name: Build Docker image
        run: docker build -t glarex-chat-app:latest .
